### ISSUE TITLE
isFileBinary has an issue for tracking "empty" files

### ISSUE THREAD

**Issue by kryptag** [Praqma/GitRepositoryDoctor#13]
Seems like Apache TIKA will always try to guess a mime type. So if none is found by extension then it reads the first couple of bytes in the file, and then it returns a mime type. In the test i made a file called "noMimeType" and Git says it's a ASCII file, While TIKA tells me its a binary file. Need to find a way to solve this issue if we still want the functionality to mark files "empty"

@bicschneider & @MadsNielsen Feedback or ideas are welcome here

**Comment by kryptag** [comment]
Checking for size doesn't seem to work `if(files.getTotalSpace() == 0L` returns false. 
![image](https://user-images.githubusercontent.com/11290150/46670706-373bbd00-cbd3-11e8-9413-18fb9145a30c.png) 
as seen here OSX tells me that the file is Zero bytes, but the method says that it's size is larger than 0 bytes

**Comment by MadsNielsen** [comment]
Hmm. Does the object have a length or isEmpty method?

**Comment by kryptag** [comment]
Checking the length of the file is working, compared to when i checked for `Size()`. It passes my tests now

**Comment by kryptag** [comment]
Closed by c5996443bc9e5ef344012f632607b7c4fdee3bf7
